### ISSUE TITLE
Soldering Guide

### ISSUE THREAD

**Issue by deedos** [thorrak/brewpi-esp8266#14]
hi. I'm wondering if is there any soldering uide published ?
thanks a lot

**Comment by thorrak** [comment]
What specifically are you interested in? Are you looking for a guide to a specific PCB, a pinout for the ESP8266 board, or something else?

**Comment by deedos** [comment]
Hi. Thanks for the quick response. I bought this one https://pcbs.io/share/46AL1 along with the components  
I 'm a bit new to eletronics guide but Ispindel is almost done and now I 'm going for this project. 

cheers

**Comment by deedos** [comment]
closing the issue. After some time I realized the missing dots of the project as a whole. As soon as possible, I'll contribute to the docs as a PR. thanks
