### ISSUE TITLE
Add “extended controls” serial response option

### ISSUE THREAD

**Issue by thorrak** [thorrak/brewpi-esp8266#17]
With a number of proposed features, we are extending the functionality beyond what BrewPi firmware offers natively. It would be good to have a single serial command to access this functionality, where the command contains a JSON encoded string with the specific functionality being accessed (and any additional payload as necessary)

**Comment by speshak** [comment]
If there is still desire for this feature (and I think it makes a lot of sense to do so), it would be fairly straight forward to model it on how I implemented [SettingsLoader](https://github.com/thorrak/brewpi-esp8266/blob/esp32/src/SettingLoader.cpp) in the PiLink refactor.  Define a new command char in [CommandProcessor](https://github.com/thorrak/brewpi-esp8266/blob/esp32/src/CommandProcessor.cpp) and dispatch to a class that handles loading & processing the JSON payload.
