### ISSUE TITLE
Testing main functions

### ISSUE THREAD

**Issue by deedos** [thorrak/brewpi-esp8266#22]
I have the controller set up and wired and fermentrack alongside with raspberry Pi (2011/2012 model, and works!).  Most of the system works but the relay seems not to be triggered whatsoever (although, when the onewire  sensors are off, the relay is triggered when in idle mode on boot).

Searching trough the hbt issue, I guees it could be the power supply (using a 2A, 5V through USB, powering the esp8266) but not reaaly sure about it.

I have double checked the wiring part of it and to debug the relay, after setting beer constant or fridge constant, it's always 9 minutes the "waiting to cool" ), so, it's very long time to wait. 

I have three questions then:

1 - Is it possible to lower thw waiting to cool time ?
2 - is there any kind of testing tool to check if the main parts of the controller works (mainly the relays) ?
3- Is there any chance to provide the power to the board (with LCD) through raspberry pi USB ?

many thanks in advance

**Comment by thorrak** [comment]
Nice! Glad to hear it works!

To your questions:

1. I don’t think so (without editing/recompiling the firmware) but I could be mistaken.

2. Yes. There should be firmware available in Fermentrack to test the wiring. I think it’s called “wiring test” or something similar - I can check later if you don’t see it. That said - be sure and disconnect any load you have before running the firmware - you don’t want to burn up a compressor while testing your build!

3. Kind of. You can do it, but depending on the LCD and how the rest of your build is wired, you may find yourself not providing sufficient power to the device.

Sent from my iPhone

On Nov 1, 2018, at 3:28 PM, Daniel Roviriego <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the controller set up and wired and fermentrack alongside with raspberry Pi (2011/2012 model, and works!). Most of the system works but the relay seems not to be triggered whatsoever (although, when the onewire sensors are off, the relay is triggered when in idle mode on boot).

Searching trough the hbt issue, I guees it could be the power supply (using a 2A, 5V through USB, powering the esp8266) but not reaaly sure about it.

I have double checked the wiring part of it and to debug the relay, after setting beer constant or fridge constant, it's always 9 minutes the "waiting to cool" ), so, it's very long time to wait.

I have three questions then:

1 - Is it possible to lower thw waiting to cool time ?
2 - is there any kind of testing tool to check if the main parts of the controller works (mainly the relays) ?
3- Is there any chance to provide the power to the board (with LCD) through raspberry pi USB ?

many thanks in advance

**Comment by deedos** [comment]
Hi Thorrak!

Many thanks for the replies. I 'll close the issue and report with feedback:

1 - Using the wire test firmware is just fine to debug, no need for changing the "waiting cool time". I found not so easy to find the firmware cause it is not in this repo. Finally I could find it using the flash tool in fermentrack but I think is easier to load it using esptool.py. Being so, the url for the firmware is here https://github.com/thorrak/brewpi-esp8266-build-test/tree/master/bin 

2 - just fine. at the end I had a faulty relay and a bad soldering at esp8266

3 - It's working but raspb pi itself has a 2A power supply. 

Cheers
