### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by speshak** [thorrak/brewpi-esp8266#49]
Add more complete documentation for class/method level details.

(I'm opening this a bit as a forewarning.  I've been working on getting Doxygen comments into as much of the codebase as I can understand.  I don't want anyone to be blindsided by a PR that touches almost every file)

**Comment by speshak** [comment]
My WIP branch: https://github.com/speshak/brewpi-esp8266/tree/cleanup_and_docs
I'm trying to keep this limited to just adding documentation, but some whitespace normalization has snuck in as well.

**Comment by thorrak** [comment]
Works for me - Whenever you have some time, send through some PRs. There
are going to be a lot of files to review as you noted. :)

**Comment by speshak** [comment]
I think the hard work for this is done.  There will be a long tail of adding & improving the documentation, but we're pointed in the right direction and this can be closed.
