### ISSUE TITLE
no WIFI setup possible

### ISSUE THREAD

**Issue by bitzebraeu** [thorrak/brewpi-esp8266#75]
Hi brewers,  I've been trying to setup my ESP8366 board several times now. Flashing the firmware works fine. I've been chosing the WIFI variant that appears on top of the list of versions you can chose from. Afterwards I can see the "ESP_........" network in my network selector. I connect, go to some webpage, my browser tries to connect to 192.168.4.1 and from then on nothing ever happens... I see some had trouble with WIFI connections before, however I could not find any similar case. Who can help? Thanks! Patrick

**Comment by thorrak** [comment]
Try flashing the WiFi Reset & Sensor Wiring Test firmware. It's located under `Other > ESP8266` in BrewFlasher, or available [here](https://web.brewflasher.com/fw/8) on BrewFlasher Web.

Once you've run the test (or if you don't have a display connected, once you've flashed it, reset the device, and waited about two minutes) then re-flash the BrewPi-ESP8266 firmware and see if it works then.

One of the things the "test" firmware does is reset the controller to a consistent state which may help to correct any potential issues with the WiFi. Alternatively, you can also try the 0.14 beta version of the firmware, which has updated WiFi manager libraries.

**Comment by bitzebraeu** [comment]
OK, will do. Just to be sure:
* test firmware: do I just flash it, or factorx reset my controller first and then flash?
* I tried the 0.14 already, insted of "ESD_..." in my network list I see "BrewPi" (or similar) and this requires a password in order to connect. Is there any?

**Comment by bitzebraeu** [comment]
I explain step by step what I did:
* flashed the "test" fimware with BrewFlasher on my Windows PC
* reset and waited
* flashed the 0.11 WIFI version
* now hooked up the controller via USB to my PI where Fermentrack is installed
* connected to "ESP_..." WIFI
* tried to load 192.168.4.1  -->  nothing happened :-(

I assmue the 0.14 version will not bring a difference. However, what is the difference between "Low delay", "no spiffs" and the blank WIFI?

**Comment by bitzebraeu** [comment]
after flashing the 0.14 version, the WIFI in my list is called "BrewPiAP" and requires a password. Which is it?

**Comment by bitzebraeu** [comment]
I repeated the process about 5 times, did not change anything. Suddenly works. (v0.11)

**Comment by thorrak** [comment]
Weird. Well - if you ever want to use the v14 firmware, the ap password is “brewpiesp”

https://github.com/thorrak/brewpi-esp8266/blob/7930d1e2051f3f2511475d43cf78d32866b6a0f5/src/Config.h#L352

**Comment by bitzebraeu** [comment]
Apart from the sp I guessed quite right :-) I'll give it a try once all is up and running..
