### ISSUE TITLE
Share room temperature between controllers

### ISSUE THREAD

**Issue by gieljnssns** [thorrak/brewpi-esp8266#90]
I have a second controller now. 
I had to make another room sensor, isn't it possible to share the room sensor from my first controller to the second?

**Comment by thorrak** [comment]
Unfortunately, no. Individual controllers are intended to have separate hardware -- though once I can re-add Inkbird support to the firmware you would be able to emulate this by having both controllers listen to a single Inkbird bluetooth sensor.
